do not require/use pyinstaller
we may introduce it later but now it breaks pipenv installation
with:
ModuleNotFoundError: No module named 'PyInstaller'"

Signed-off-by: Radovan Bast <bast@users.noreply.github.com>